### ISSUE TITLE
Extend Custom Approval Task with Specified Result Fields

### ISSUE THREAD

**Issue by zmotso** [KubeRocketCI/tekton-custom-task#16]
We require the extension of the existing Custom Approval Task functionality to include the ability to return specific results upon completion. This task extension is inspired by examples found at the following URLs:
- https://github.com/automatiko-io/automatiko-approval-task?tab=readme-ov-file#results
- https://tekton.dev/docs/pipelines/customruns/#monitoring-results

The Custom Approval Task must now support returning results upon completion. The results should include the following fields:
- `approved`: A boolean value (`true` or `false`) indicating whether the task was approved.
- `approvedBy`: A string value indicating the identity of the approver.
- `comment`: An optional string value for any comments provided by the approvers.

Acceptance Criteria
- The existing Custom Approval Task functionality is extended to return results upon completion.
- The results must include the specified fields: `approved` (bool), `approvedBy` (string), and `comment` (string), where `comment` is optional.
- Proper validation must be in place for the `approved` and `approvedBy` fields.
- The extended functionality must be tested to ensure the results are returned as expected and adhere to the specified format.

**Comment by SergK** [comment]
Addressed in https://github.com/KubeRocketCI/tekton-custom-task/pull/17
